stages:
  - build
  - deploy

build-check:
  stage: build
  only: [ master ]
  script:
    - earthly +build

package-all:
  stage: build
  only: [ tags ]
  script:
    - earthly +package
  artifacts:
    paths:
      - libemergent-dev_*.deb

deploy-packages:
  stage: deploy
  when: on_success
  only: [ tags ]
  dependencies: [ package-all ]
  script:
    - scp libemergent-dev_*.deb $DEPLOY_DOWNLOADS/libemergent/
    - phi-deploy libemergent-dev_*.deb bionic oss
    - phi-deploy libemergent-dev_*.deb focal oss
