include:
  - project: 'core/common'
    file: '/templates/ci.yml'

variables:
  COMPONENT: oss

package-emergent:
  extends: [ .build-packages ]
  variables: { MODULE: emergent, MATCH: /^v.*$/ }

deploy-emergent:
  needs: [ package-emergent ]
  extends: [ .deploy-simple ]
  variables: { MATCH: /^v.*$/ }
