name: gitlab-sync

on: 
  - push
  - delete
  - workflow_dispatch

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Gitlab Sync
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: wangchucheng/git-repo-sync@v0.1.0
      with:
        target-url: <target-url>
        target-username: <target-username>
        target-token: <target-token>
