name: gitlab-sync

on: 
  - push
  - delete
  - workflow_dispatch

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Gitlab Sync
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: sync
      shell: bash
      env:
        TARGET_USERNAME: ${{ secrets.TARGET_USERNAME }}
        TARGET_TOKEN: ${{ secrets.TARGET_TOKEN }}
        TARGET_URL: ${{ secrets.TARGET_URL }}
      run: |
        echo ${{ secrets.TARGET_URL }}
        git remote add target https://$TARGET_USERNAME:$TARGET_TOKEN@$TARGET_URL
        git push --all target
        git push --tags target
